---
sidebar: sidebar 
permalink: task-set-up-gcnv.html 
keywords: setup, set up, api, service account, requirements, permissions, google cloud netapp volumes, gcnv, bluexp. netapp console 
summary: O NetApp Console precisa de acesso à API do Google Cloud NetApp Volumes e das permissões corretas por meio de uma conta de serviço do Google Cloud. 
---
= Configurar o Google Cloud NetApp Volumes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O NetApp Console precisa das permissões corretas por meio de uma conta de serviço do Google Cloud.

Conclua as seguintes tarefas para que o NetApp Console possa acessar seu projeto do Google Cloud.

* Se você ainda não tiver uma conta de serviço, crie uma nova.
* Conceder acesso para fins de representação indevida.
* Conceda a função IAM no projeto compartilhado.




== Configurar uma conta de serviço

. No console do Google Cloud, https://console.cloud.google.com/iam-admin/serviceaccounts["vá para a página de contas de serviço"^] .
. Clique em *Selecionar um projeto*, escolha seu projeto e clique em *Abrir*.
. Para criar uma conta de serviço, faça o seguinte:
+
.. Clique em *Criar conta de serviço*.
.. Digite o nome da conta de serviço (nome de exibição amigável) e a descrição.
+
O Google Cloud Console gera um ID de conta de serviço com base nesse nome.  Edite o ID se necessário - você não poderá alterá-lo posteriormente.

.. Clique em *Criar e continuar*.
.. Na lista de funções, selecione a função *Administrador do Google Cloud NetApp Volumes * ou *Visualizador do Google Cloud NetApp *.
.. Selecione *Continuar*.
.. Conceda acesso de representação a esta conta de serviço: credentials-sa@wf-production-netapp.iam.gserviceaccount.com. Para mais detalhes, veja https://cloud.google.com/iam/docs/create-short-lived-credentials-direct#sa-credentials-jwt["Criar um JSON Web Token (JWT) autoassinado"^] .
.. Clique em *CONCLUÍDO* na parte inferior da página e continue para a próxima etapa.






== VPC compartilhada

Em cada projeto adicional do GCP que usará a conta de serviço, faça o seguinte:

. Na _página IAM_, selecione o projeto de host da VPC compartilhada no menu suspenso do projeto.
. Clique em *Adicionar Principal*.
. No campo Novos principais, insira o endereço de e-mail da sua conta de serviço.
. Na lista suspensa Selecionar uma função, escolha a função *Administrador do Google Cloud NetApp Volumes *.
. Clique em *Salvar*.


Para etapas detalhadas, consulte a documentação do Google Cloud:

* link:https://cloud.google.com/iam/docs/creating-managing-service-accounts["Criação e gerenciamento de contas de serviço"^]
* link:https://cloud.google.com/iam/docs/roles-permissions/netapp["Funções e permissões do Google Cloud NetApp Volumes"^]
* link:https://cloud.google.com/iam/docs/granting-changing-revoking-access["Concedendo, alterando e revogando acesso a recursos"^]




== Solução de problemas

Caso ocorra um erro, a política *iam.disableCrossProjectServiceAccountUsage* poderá ser aplicada.  Para corrigir isso, faça o seguinte:

. No console do Google Cloud, acesse o https://console.cloud.google.com/iam-admin/orgpolicies["Página de políticas da organização"^] .
. Localize a política *Desativar o uso de contas de serviço entre projetos* e desative-a.


.O que vem a seguir?
link:task-add-roles.html["Atribua funções aos Google Cloud NetApp Volumes."].
